### ISSUE TITLE
[semanage] [python-sepol] semanage crashes on systems without policy

### ISSUE THREAD

**Issue by schmittlauch** [SELinuxProject/selinux#81] opened 2018-02-26 10:59 UTC
The semanage tool crashes on systems without installed policies:

```
# semanage
Traceback (most recent call last):
  File "/usr/sbin/semanage", line 28, in <module>
    import seobject
  File "/usr/lib/python3.4/site-packages/seobject.py", line 1039, in <module>
    class portRecords(semanageRecords):
  File "/usr/lib/python3.4/site-packages/seobject.py", line 1041, in portRecords
    valid_types = list(list(sepolicy.info(sepolicy.ATTRIBUTE, "port_type"))[0]["types"])
  File "/usr/lib/python3.4/site-packages/sepolicy/__init__.py", line 196, in <genexpr>
    return ({
  File "/usr/lib/python3.4/site-packages/setools/typeattrquery.py", line 65, in results
    for attr in self.policy.typeattributes():
AttributeError: 'NoneType' object has no attribute 'typeattributes'
```

This is caused by sepol (the python module) setting the global _pol variable to `None` – something setools.TypeAttributeQuery can't deal with.

### platform details:

python3-modules used with python-3.4.3 
distribution: mer
libselinux/ libsepol/ libsemanage/ policycoreutils: v2.7
python3-setools: 4.1.1

disclaimer: policycoreutils and setools are customly packaged, this is a possible (but unlikely) error source

**Comment by stephensmalley** [comment] 2018-02-26 15:08
Reproduced upstream, e.g. just mv /etc/selinux /etc/selinux.old and try running semanage as above.

**Comment by fishilico** [comment] 2018-08-04 18:01
This behavior is mainly due to having `valid_types = list(list(sepolicy.info(...` in class definitions instead of having them in class constructors (in `seobject.py`). This makes it harder to catch the fact that no policy is loaded.
I suggest moving the `valid_types` definitions to class constructors, to give importers of seobject.py the possibility to display a nice error message if no policy is loaded (or to specify a policy to be loaded).
What do you think of this?

**Comment by bachradsusi** [comment] 2019-01-04 21:44
I should probably drop the reference to this issue from my working commits in order to prevent another automatic closing. Sorry for the noise.

**Comment by bachradsusi** [comment] 2019-01-14 13:57
Fixed by https://github.com/SELinuxProject/selinux/commit/a73b0bba1a52adec3cfe654f726388a68b73e2d3 https://github.com/SELinuxProject/selinux/commit/e718c2ab77f8f3347bd2289502797bb978c33e3e

**Closed by bachradsusi** 2019-01-14 13:57 UTC

**Comment by devZer0** [comment] 2019-02-10 10:31
on recent debian 9.7, i'm also getting this. some note about the missing package would be nice, i found this via strace...

**Comment by renannprado** [comment] 2020-06-30 20:00
@devZer0 would be nice if you say which is the missing package...

I have this problem in Ubuntu still.

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

**Comment by JeanCarlosChavarriaHughes** [comment] 2020-09-16 04:15
Facing the same issue:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```

```
Python 3.6.9
```

```
pip 20.2.3
```

```
python3-setools is already the newest version (4.1.1-3)
```

**Comment by garthk** [comment] 2024-07-10 02:53
G'day! If you're reading this because some other `semanage` command crashed for you with an `AttributeError` below a line of code using `self.policy`, try installing `selinux-policy-targeted`:

```bash
dnf install selinux-policy-targeted
```

I triggered the error trying `sepolicy generate` with `python3-policycoreutils-2.9-26`:

```plaintext
bash-4.4# sepolicy generate --customize
Traceback (most recent call last):
  File "/usr/bin/sepolicy", line 684, in <module>
    args.func(args)
  File "/usr/bin/sepolicy", line 518, in generate
    mypolicy = policy(args.name, args.policytype)
  File "/usr/lib/python3.6/site-packages/sepolicy/generate.py", line 200, in __init__
    self.all_roles = get_all_roles()
  File "/usr/lib/python3.6/site-packages/sepolicy/__init__.py", line 927, in get_all_roles
    roles = [str(x) for x in q.results() if str(x) != "object_r"]
  File "/usr/lib/python3.6/site-packages/sepolicy/__init__.py", line 927, in <listcomp>
    roles = [str(x) for x in q.results() if str(x) != "object_r"]
  File "/usr/lib64/python3.6/site-packages/setools/rolequery.py", line 65, in results
    for r in self.policy.roles():
AttributeError: 'NoneType' object has no attribute 'roles'
```
