### ISSUE TITLE
ERROR 'syntax error' at token 'domain_read_all_domains_state'

### ISSUE THREAD

**Issue by brianjmurrell** [SELinuxProject/selinux#290] opened 2021-06-10 18:07 UTC
Trying to compile a policy module I get all kinds of warnings and then a final error.  This module used to compile in 2019 when I last needed to compile it.

I'm using selinux-policy-devel-3.13.1-268.el7_9.2.noarch as that's what's currently available on my CentOS 7.9 machine.

### Steps to Reproduce:
```
cat <<EOF > asterisk_local.te
module asterisk_local 1.3;

require {
        type unreserved_port_t;
        type ephemeral_port_t;
        type pop_port_t;
        type asterisk_t;
        class tcp_socket name_connect;
}

#============= asterisk_t ==============

#!!!! This avc can be allowed using the boolean 'nis_enabled'
allow asterisk_t unreserved_port_t:tcp_socket name_connect;
allow asterisk_t ephemeral_port_t:tcp_socket name_connect;
allow asterisk_t pop_port_t:tcp_socket name_connect;

domain_read_all_domains_state(asterisk_t)
EOF
make -f /usr/share/selinux/devel/Makefile asterisk_local.pp
```

I get as a result:

```
find: unknown predicate `-f'
Compiling targeted asterisk_local module
tmp/all_interfaces.conf:1676: Warning: $0($*) has been deprecated.
tmp/all_interfaces.conf:1690: Warning: $0($*) has been deprecated.
tmp/all_interfaces.conf:2325: Warning: $0($*) has been deprecated.
tmp/all_interfaces.conf:2706: Warning: $0($*) has been deprecated, please use certwatch_run() instead.
tmp/all_interfaces.conf:3757: Warning: $0($*) has been deprecated
tmp/all_interfaces.conf:3781: Warning: $0($*) has been deprecated
tmp/all_interfaces.conf:5735: Warning: $0($*) has been deprecated, use corosync_admin() instead.
tmp/all_interfaces.conf:9060: Warning: $0($*) has been deprecated.
tmp/all_interfaces.conf:11605: Warning: $0($*) has been deprecated.
tmp/all_interfaces.conf:11631: Warning: $0($*) has been deprecated.
tmp/all_interfaces.conf:13008: Warning: $0($*) has been deprecated, use cobbler_admin() instead.
tmp/all_interfaces.conf:13186: Warning: $0($*) has been deprecated.
tmp/all_interfaces.conf:16529: Warning: $0($*) has been deprecated
tmp/all_interfaces.conf:24154: Warning: $0($*) has been deprecated.
tmp/all_interfaces.conf:26435: Warning: $0($*) has been deprecated.
tmp/all_interfaces.conf:27458: Warning: $0(): has been deprecated, please use files_exec_etc_files() instead.
tmp/all_interfaces.conf:27729: Warning: $0($*) has been deprecated.
/usr/bin/checkmodule:  loading policy configuration from tmp/asterisk_local.tmp
asterisk_local.te:25:ERROR 'syntax error' at token 'domain_read_all_domains_state' on line 1065:

domain_read_all_domains_state(asterisk_t)
```

Not being an SELinux "expert" I'm not even really sure what that error is trying to tell me.  Any explanations?

**Comment by wrabcak** [comment] 2021-06-11 09:37
Hello, 

I tried to reproduce it on the RHEL-7.9 with the same policy and it works for me with few changes. 
```

# rpm -q selinux-policy
selinux-policy-3.13.1-268.el7_9.2.noarch
# uname -a 
Linux localhost 3.10.0-1160.6.1.el7.x86_64 #1 SMP Wed Oct 21 13:44:38 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

cat <<EOF > asterisk_local.te
policy_module(asterisk_local,1.3)

gen_require(`
        type unreserved_port_t;
        type ephemeral_port_t;
        type pop_port_t;
        type asterisk_t;
')

#============= asterisk_t ==============

#!!!! This avc can be allowed using the boolean 'nis_enabled'
allow asterisk_t unreserved_port_t:tcp_socket name_connect;
allow asterisk_t ephemeral_port_t:tcp_socket name_connect;
allow asterisk_t pop_port_t:tcp_socket name_connect;

domain_read_all_domains_state(asterisk_t)
EOF

# make -f /usr/share/selinux/devel/Makefile asterisk_local.pp
# semodule -i asterisk_local.pp

# semodule -lfull | grep asterisk_local
400 asterisk_local    pp

# sesearch -A -s asterisk_t -t asterisk_t -t domain -c file -p read
Found 3 semantic av rules:
   allow domain abrt_t : file { ioctl read getattr lock open } ; 
   allow asterisk_t asterisk_t : file { ioctl read write getattr lock append open } ; 
   allow asterisk_t domain : file { ioctl read getattr lock open } ; 
```

Did you install any 3rd party policy ? Do you have any SELinux custom modifications applied on the system? 

Thanks,
Lukas.

**Comment by zpytela** [comment] 2021-06-11 09:48
@brianjmurrell no change has been made in selinux-policy nor in userpace tools which would effect modules compilation in this way.

There is one usage difference: with `module`, you need to declare all lexical types. Please follow the example shown by @wrabcak if you want to make use of existing interfaces.

**Comment by brianjmurrell** [comment] 2021-06-11 19:44
> works for me with few changes.

So there seems to be a difference in the format of the policy file, for starters.  But even following the new format, I still get a slew of errors.  For the policy file:

```
policy_module(asterisk_local,1.4)

gen_require(`
        type kernel_t;
        type asterisk_t;
        type unreserved_port_t;
        type ephemeral_port_t;
        type pop_port_t;
        class tcp_socket name_connect;
        class dir search;
')

#============= asterisk_t ==============
allow asterisk_t kernel_t:dir search;

#!!!! This avc can be allowed using the boolean 'nis_enabled'
allow asterisk_t unreserved_port_t:tcp_socket name_connect;
allow asterisk_t ephemeral_port_t:tcp_socket name_connect;
allow asterisk_t pop_port_t:tcp_socket name_connect;

domain_read_all_domains_state(asterisk_t)
```
I still get the following errors:

```
# make -f /usr/share/selinux/devel/Makefile asterisk_local.pp
find: unknown predicate `-f'
Compiling targeted asterisk_local module
tmp/all_interfaces.conf:1676: Warning: $0($*) has been deprecated.
tmp/all_interfaces.conf:1690: Warning: $0($*) has been deprecated.
tmp/all_interfaces.conf:2325: Warning: $0($*) has been deprecated.
tmp/all_interfaces.conf:2706: Warning: $0($*) has been deprecated, please use certwatch_run() instead.
tmp/all_interfaces.conf:3757: Warning: $0($*) has been deprecated
tmp/all_interfaces.conf:3781: Warning: $0($*) has been deprecated
tmp/all_interfaces.conf:5735: Warning: $0($*) has been deprecated, use corosync_admin() instead.
tmp/all_interfaces.conf:9060: Warning: $0($*) has been deprecated.
tmp/all_interfaces.conf:11605: Warning: $0($*) has been deprecated.
tmp/all_interfaces.conf:11631: Warning: $0($*) has been deprecated.
tmp/all_interfaces.conf:13008: Warning: $0($*) has been deprecated, use cobbler_admin() instead.
tmp/all_interfaces.conf:13186: Warning: $0($*) has been deprecated.
tmp/all_interfaces.conf:16529: Warning: $0($*) has been deprecated
tmp/all_interfaces.conf:24154: Warning: $0($*) has been deprecated.
tmp/all_interfaces.conf:26435: Warning: $0($*) has been deprecated.
tmp/all_interfaces.conf:27458: Warning: $0(): has been deprecated, please use files_exec_etc_files() instead.
tmp/all_interfaces.conf:27729: Warning: $0($*) has been deprecated.
/usr/bin/checkmodule:  loading policy configuration from tmp/asterisk_local.tmp
asterisk_local.te:28:ERROR 'syntax error' at token 'domain_read_all_domains_state' on line 3369:

domain_read_all_domains_state(asterisk_t)
/usr/bin/checkmodule:  error(s) encountered while parsing configuration
make: *** [tmp/asterisk_local.mod] Error 1
```

> Did you install any 3rd party policy ? Do you have any SELinux custom modifications applied on the system?

No to both of those, to the best of my recollection.  I do have other local policies installed though.

**Comment by brianjmurrell** [comment] 2021-06-11 20:16
Resolved it.  A few issues:
- I had a file named `-f` in the dir with the policy file
- I had a file with a name with spaces in the same dir as the policy file
- I had a `tmp/` directory in the same dir as the policy file with the following contents:
```
-rw-r--r--. 1 root root 609762 May 11 12:51 all_interfaces.conf
-rw-r--r--. 1 root root  50424 Jun 11 16:11 asterisk_local.tmp
-rw-r--r--. 1 root root   8038 Oct 24  2016 bz1350894_local.tmp
-rw-r--r--. 1 root root   8072 Sep 30  2016 bz1379998_local.tmp
-rw-r--r--. 1 root root   8017 Oct  3  2016 bz1381234_local.tmp
-rw-r--r--. 1 root root   8129 Oct  8  2016 bz1382955_local.tmp
-rw-r--r--. 1 root root   8163 Oct  9  2016 bz1383018_local.tmp
-rw-r--r--. 1 root root   8123 Nov  7  2016 bz1389261_local.tmp
-rw-r--r--. 1 root root   8024 Nov  8  2016 bz1393013_local.tmp
-rw-r--r--. 1 root root   8000 Nov  8  2016 bz1393015_local.tmp
-rw-r--r--. 1 root root   8003 Nov  8  2016 bz1393020_local.tmp
-rw-r--r--. 1 root root   8003 Nov  8  2016 bz1393030_local.tmp
-rw-r--r--. 1 root root   8258 Jan 25  2018 conman_local.tmp
-rw-r--r--. 1 root root   9189 Jun 13  2018 fail2ban_local.tmp
-rw-r--r--. 1 root root     32 May 11 12:51 iferror.m4
-rw-r--r--. 1 root root  10793 Jan 22  2019 ilinx_local.tmp
-rw-r--r--. 1 root root   8617 Jun 13  2018 local_local.tmp
-rw-r--r--. 1 root root   8139 Jun  5  2017 log_passwords_local.tmp
-rw-r--r--. 1 root root   8115 Jan 23  2018 named-dhcp_local.tmp
-rw-r--r--. 1 root root   8121 May 30  2018 rpc.gssd_local.tmp
-rw-r--r--. 1 root root   8116 Jul 11  2017 ufdbGuard_local.tmp
```

which all look to be related to other policies.  After removing all of the above, `make -f /usr/share/selinux/devel/Makefile asterisk_local.pp` did not complain about any of the previous problems.

I was left with another `tmp/` dir in the dir I ran the `make` in with the following contents:

```
-rw-r--r--. 1 root root 9851577 Jun 11 16:12 all_interfaces.conf
-rw-r--r--. 1 root root   51594 Jun 11 16:12 asterisk_local.tmp
-rw-r--r--. 1 root root      32 Jun 11 16:12 iferror.m4
```

**Comment by fishilico** [comment] 2021-09-27 08:17
Closing the issue, at it was resolved.

**Closed by fishilico** 2021-09-27 08:17 UTC
