### ISSUE TITLE
matchpathcon.c:matchpathcon_init_prefix - expecting 1 byte in a region of size 0

### ISSUE THREAD

**Issue by dilyanpalauzov** [SELinuxProject/selinux#311] opened 2021-09-22 17:21 UTC
Using gcc (GCC) 11.2.1 20210918 calling `make` in the root of the unpacked selinux-3.3-rc1.tar.gz, fails with:
```
make[2]: Entering directory '/src/selinux/selinux-3.3-rc1/libselinux/src'
cc -O2 -Werror -Wall -Wextra -Wmissing-format-attribute -Wmissing-noreturn -Wpointer-arith -Wshadow -Wstrict-prototypes -Wundef -Wunused -Wwrite-strings -fno-common -I../include -D_GNU_SOURCE -DNO_ANDROID_BACKEND -I/usr/local/include  -c -o matchpathcon.o matchpathcon.c
In file included from matchpathcon.c:5:
matchpathcon.c: In function ‘matchpathcon_init_prefix’:
selinux_internal.h:38:25: error: ‘pthread_setspecific’ expecting 1 byte in a region of size 0 [-Werror=stringop-overread]
   38 |                         pthread_setspecific(KEY, VALUE);        \
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
matchpathcon.c:359:9: note: in expansion of macro ‘__selinux_setspecific’
  359 |         __selinux_setspecific(destructor_key, (void *)1);
      |         ^~~~~~~~~~~~~~~~~~~~~
In file included from selinux_internal.h:2,
                 from matchpathcon.c:5:
/usr/local/lib/gcc/x86_64-pc-linux-gnu/11.2.1/include-fixed/pthread.h:1317:12: note: in a call to function ‘pthread_setspecific’ declared with attribute ‘access (none, 2)’
 1317 | extern int pthread_setspecific (pthread_key_t __key,
      |            ^~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:167: matchpathcon.o] Error 1
make[2]: Leaving directory '/src/selinux/selinux-3.3-rc1/libselinux/src'
make[1]: *** [Makefile:48: all] Error 1
make[1]: Leaving directory '/src/selinux/selinux-3.3-rc1/libselinux'
make: *** [Makefile:35: all] Error 1

```

**Comment by dilyanpalauzov** [comment] 2021-09-22 17:26
This applies to 3.3-rc2, too.

**Comment by cgzones** [comment] 2021-09-24 17:47
This is caused by the `access` attribute annotation of `pthread_setspecific()` by the libc used (Debian sid and Fedora 34 do not have any annotation yet).

GCC [defines](https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html) the `none` mode of `access` as:

> The access mode none specifies that the pointer to which it applies is not used to access the referenced object at all. Unless the pointer is null the pointed-to object must exist and have at least the size as denoted by the size-index argument. The object need not be initialized. The mode is intended to be used as a means to help validate the expected object size, for example in functions that call __builtin_object_size. See Object Size Checking. 

As `(void*)1` is passed, it is obviously not a null-pointer, and no object exists at the address.

As `pthread_getspecific()` is never called the actual value does not matter, so it seems not to be a libselinux bug.

I see two options:

1. Ignore this warning via [GCC pragmas](https://gcc.gnu.org/onlinedocs/gcc/Diagnostic-Pragmas.html)

2. Pass a valid pointer (e.g. to a `static char dummy`)

**Comment by dilyanpalauzov** [comment] 2021-09-24 17:59
I run a Linux from Scratch with Libc 2.34.

**Comment by fishilico** [comment] 2021-09-27 07:52
Hello,
I quickly took a look and I agree it seems to be a compiler issue (meaning: if the warning is ignored with `-Wno-stringop-overread`, the build code should work fine). Nevertheless I agree it should be fixed in libselinux, for example with the suggested option 2 (passing a valid pointer to dummy data, adding a comment to the code which indicates that this is done in order to make each thread runs `matchpathcon_thread_destructor` when it exits).

Do you want to work on a patch to fix this?

By the way, discussion and patches are preferred on the mailing list (cf. <https://github.com/SELinuxProject/selinux/blob/master/CONTRIBUTING.md>).

Thanks for this clear bug report!

**Comment by dilyanpalauzov** [comment] 2021-09-27 09:10
> Do you want to work on a patch to fix this?

No.

**Closed** 2021-11-11 21:58 UTC
