### ISSUE TITLE
semodule_deps show wrong dependencies

### ISSUE THREAD

**Issue by sopos** [SELinuxProject/selinux#64] opened 2017-09-27 10:32 UTC
Particularly showed requirements are shifted by one index.

```
cat > module1.te << EOF
module module1 1.0;
require {
        type bin_t;
}
type module1_t;
EOF
cat > module2.te << EOF
module module2 1.0;
require {
        type bin_t;
}
type module2_t;
EOF
cat > module3.te << EOF
module module3 1.0;
require {
        type module1_t;
}
type module3_t;
EOF
cat > module4.te << EOF
module module4 1.0;
require {
        type module2_t;
}
type module4_t;
EOF
cat > module5.te << EOF
module module5 1.0;
require {
        type module1_t;
        type module4_t;
}
type module5_t;
EOF
cat > module6.te << EOF
module module6 1.0;
require {
        type module3_t;
        type module4_t;
}
type module6_t;
EOF
make -f /usr/share/selinux/devel/Makefile
semodule -E base

semodule_deps base.pp module1.pp module2.pp module3.pp module4.pp module5.pp module6.pp
module: module1
        [no dependencies]
module: module2
        [no dependencies]
module: module3
        module2
module: module4
        module3
module: module5
        module2
        module5
module: module6
        module4
        module5
}
```
Moreover there is `}` at the end.

I have taken a quick look at the code but have not been able to identify the buggy part. The output seems to be simple enough and sane so I suspect the `generate_requires` function.

**Comment by stephensmalley** [comment] 2017-09-27 17:06
Hmm...that's interesting.  I can reproduce the same results going all the way back to libsepol-1.15 and policycoreutils-1.33 on CentOS 5.11.  I don't have anything older handy to test on at the moment.  So this is a very old bug.  Also, semodule_deps is obsoleted by CIL modules, which don't have explicit requires.  We would like to stop using binary modules altogether, see #54. Thus, I am inclined to just drop semodule_deps; it has never been used upstream or in Fedora/RHEL; how is it being used elsewhere (and how is it that it has been broken for so long without any report)? @jwcart2

**Comment by stephensmalley** [comment] 2017-09-27 17:07
@karlwmacmillan Any clues on this?

**Comment by karlwmacmillan** [comment] 2017-09-29 20:30
No idea - it had to work at some point because I wrote that to debug the requirements resolution code. But I bet it's not been touched since then.

**Comment by sopos** [comment] 2017-09-30 09:51
It was probably never used by anyone, I'm just filling white spaces in the test coverage so I came to this one too. There's really no need to fix it if there is no consumer. If you decide not to fix it I'll just drop the test. I just want to have kind of official statement.

**Comment by stephensmalley** [comment] 2017-10-03 14:46
I have posted a patch to selinux list to remove semodule_deps; it will be merged in a few days unless there is a strong objection (and someone can actually fix it).

**Closed** 2017-10-12 18:22 UTC
