### ISSUE TITLE
Setting booleans causes duplicate ports in semanage listings

### ISSUE THREAD

**Issue by carlosefr** [SELinuxProject/selinux#50] opened 2017-03-27 19:44 UTC
I've noticed a strange interaction with custom ports and booleans. After setting a boolean, the list of ports for a particular type (which has been customized) shows duplicate entries.

Example:
```
$ semanage port -a -t http_port_t -p tcp 12345
$ semanage port -l | grep http_port_t
http_port_t                    tcp      12345, 80, 81, 443, 488, 8008, 8009, 8443, 9000
$ setsebool -P zebra_write_config false
$ semanage port -l | grep http_port_t
http_port_t                    tcp      12345, 12345, 80, 81, 443, 488, 8008, 8009, 8443, 9000
$ setsebool -P zebra_write_config false
$ semanage port -l | grep http_port_t
http_port_t                    tcp      12345, 12345, 12345, 80, 81, 443, 488, 8008, 8009, 8443, 9000
```
As can be seen, each time a boolean is set persistently (it doesn't matter which boolean or which state), the custom port `12345` is duplicated. Running `semodule -B` clears the duplicates.

However, if only the local customizations are listed, the port is always listed only once:
```
$ semanage port -l -C
SELinux Port Type              Proto    Port Number

http_port_t                    tcp      12345
```

I'm using CentOS:
```
$ cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core)
$ rpm -qf /usr/sbin/semanage 
policycoreutils-python-2.5-11.el7_3.x86_64
```

**Comment by stephensmalley** [comment] 2017-04-06 17:09
Thanks for the bug report.  Did you open a bug on Red Hat's bugzilla too?  If not, would recommend it.
We generally prefer that people raise issues on the mailing list as not everyone follows github; subscribe via selinux-join AT tycho.nsa.gov; you can always open an issue here and then post a summary to the list. I can reproduce with the upstream, but the most obvious fix would impose a non-trivial performance cost on setsebool, so will have to investigate further.

**Comment by carlosefr** [comment] 2017-04-06 17:20
I din't open a bug in Red Hat's bugzilla because I'm using CentOS and don't known their policy on this.

I'll repost to that list with a link to this issue.

**Comment by stephensmalley** [comment] 2017-04-06 17:21
Well, it is reproducible on Fedora, and they take bugs against Fedora certainly.

**Comment by carlosefr** [comment] 2017-04-06 17:24
Ok, I guess I can spin up a Fedora VM quickly enough. :)

**Comment by stephensmalley** [comment] 2017-04-06 17:31
BTW, the root cause seems to be commit e5aaa01f81afa278cce79bd59ebfdb80a32e4e5a (mea culpa), which was an attempt to optimize setting booleans by not re-linking modules in that case.  The problem though is that it seems the existing linked policy already includes the local customizations (e.g. your port addition) and then we end up adding it again to the final policy.  Not sure yet if that was always a problem since that commit or if it got brought it when CIL was merged.

**Comment by carlosefr** [comment] 2017-04-06 18:00
Red Hat Bugzilla issue here: https://bugzilla.redhat.com/show_bug.cgi?id=1439875

**Comment by stephensmalley** [comment] 2017-04-11 18:41
Commit b61922f resolves this in the simplest way possible, i.e. reverting the breaking change, but results in a significant slowdown and memory overhead for setsebool -P.  A follow-on patch has been posted to the list that should restore the optimization without yielding this incorrect behavior.

**Closed** 2017-04-12 20:10 UTC
